apiVersion: apps/v1
kind: Deployment
metadata:
  name: 03munsh
  labels:
    app: munsh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: munsh
  template:
    metadata:
      labels:
        app: munsh
    spec:
      containers:
      - name: 03munsh
        image: munsh/docimg3:latest
        ports:
        - containerPort: 80
